package de.ledgerline.app.core.crypto

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import java.io.ByteArrayOutputStream

/**
 * Byte-exact **known-answer tests** for the zero-knowledge primitives against an INDEPENDENT
 * libsodium reference (PyNaCl — a different binding to the same libsodium C lib). Fixtures live
 * in `androidTest/assets/crypto_kat.json`, generated by `tools/gen_crypto_kat.py` (PyNaCl). A mismatch here
 * means Android's `SodiumCrypto` wrapper would fail to interoperate with Web/iOS data (Phase 8).
 *
 * These run on-device (libsodium native), so they're instrumented, not JVM-unit.
 */
@RunWith(AndroidJUnit4::class)
class CryptoKatTest {
    private val crypto = SodiumCrypto()

    private val fixture by lazy {
        val ctx = InstrumentationRegistry.getInstrumentation().context
        val text = ctx.assets.open("crypto_kat.json").bufferedReader().use { it.readText() }
        Json.parseToJsonElement(text).jsonObject
    }

    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { ((s[it * 2].digitToInt(16) shl 4) or s[it * 2 + 1].digitToInt(16)).toByte() }

    private fun str(section: String, key: String) = fixture[section]!!.jsonObject[key]!!.jsonPrimitive.content
    private fun bytes(section: String, key: String) = hex(str(section, key))

    /** Argon2id (crypto_pwhash, ALG_ARGON2ID13): passphrase + salt + ops/mem → exact 32-byte VK. */
    @Test fun argon2id_vk_matches_reference() {
        val vk = crypto.deriveKek(
            passphrase = str("argon2id", "passphrase").toByteArray(),
            salt = bytes("argon2id", "salt_hex"),
            opsLimit = str("argon2id", "ops").toLong(),
            memLimit = str("argon2id", "mem").toLong(),
        )
        assertArrayEquals(bytes("argon2id", "vk_hex"), vk)
    }

    /** secretbox: Android seals byte-identically AND opens the reference ciphertext. */
    @Test fun secretbox_seal_and_open_match_reference() {
        val key = bytes("secretbox", "key_hex")
        val nonce = bytes("secretbox", "nonce_hex")
        val pt = str("secretbox", "plaintext").toByteArray()
        assertArrayEquals(bytes("secretbox", "cipher_hex"), crypto.secretBoxSealForTest(pt, nonce, key))
        assertArrayEquals(pt, crypto.secretBoxOpen(bytes("secretbox", "cipher_hex"), nonce, key))
    }

    /** secretstream (XChaCha20-Poly1305) + framing: Android decrypts a reference blob byte-exact. */
    @Test fun secretstream_decrypts_reference_blob() {
        val vk = bytes("secretstream", "vk_hex")
        val encFileKey = str("secretstream", "encFileKey")
        val blob = bytes("secretstream", "blob_hex")
        val dec = crypto.contentDecryptor(encFileKey, vk)
        dec.start(blob.copyOfRange(0, dec.headerBytes))
        val out = ByteArrayOutputStream()
        var off = dec.headerBytes
        while (off < blob.size) {
            val len = crypto.readU32le(blob, off); off += 4
            val (msg, final) = dec.decryptFrame(blob.copyOfRange(off, off + len)); off += len
            out.write(msg)
            if (final) break
        }
        assertArrayEquals(bytes("secretstream", "plaintext_hex"), out.toByteArray())
    }

    /**
     * sealManifest byte-exactness is composed of three parts each covered elsewhere: canonical JSON
     * (`CanonicalJsonTest`), the secretbox layer (KAT above), and Padmé padding (`PadmeTest`). This
     * asserts the envelope wrapper the recipient parses: an Android seal opens back to canonical JSON.
     */
    @Test fun seal_manifest_envelope_roundtrips() {
        val vk = ByteArray(32) { (it + 3).toByte() }
        val json = """{"a":1,"b":"x"}"""
        val sealed = crypto.sealManifest(json, vk)
        assertEquals(true, sealed.contains("\"suite\":1"))
        assertEquals(true, crypto.openManifest(sealed, vk)!!.startsWith(json))
    }
}
